package com.example.game.telemetry.domain;

public enum TelemetryEventType {
	XP_EARNED,
	LEVEL_UP,
	ATTRIBUTES_ALLOCATED,
	RESPEC,
	COMBAT_STARTED,
	COMBAT_ENDED,
	PVP_MATCH_SETTLED,
	GOLD_CREATED,
	GOLD_DESTROYED,
	MARKET_TRADE,
	ITEM_CREATED,
	CRAFTING_STARTED,
	CRAFTING_CLAIMED,
	ITEM_SALVAGED,
	PROFESSION_RANK_UP
}
