package com.example.game.combat.domain;

public enum CombatEventType {
	PLAYER_ATTACK,
	PLAYER_MISS,
	PLAYER_CRIT,
	PLAYER_DEFEND,
	PLAYER_POTION,
	PLAYER_RETREAT_SUCCESS,
	PLAYER_RETREAT_FAIL,
	ENEMY_ATTACK,
	ENEMY_MISS,
	COMBAT_WON,
	COMBAT_LOST,
	COMBAT_ESCAPED,
	INFO
}
