package com.example.game.activity.domain;

/**
 * Personal activity event kinds shown in the persistent feed.
 */
public enum ActivityType {
	COMBAT_VICTORY,
	LEVEL_UP,
	ITEM_FOUND,
	EXPEDITION_COMPLETED,
	EXPEDITION_CLAIMED,
	MARKET_SOLD,
	MARKET_BOUGHT,
	MARKET_CANCELLED,
	MASTERY_UNLOCK,
	TECHNIQUE_UNLOCK,
	ARENA_VICTORY,
	ARENA_DEFEAT,
	DUEL_RESULT,
	CRAFTING_STARTED,
	CRAFTING_CLAIMED,
	PROFESSION_RANK_UP,
	ITEM_SALVAGED,
	MARKET_LISTING_FEE,
	MARKET_SALE,
	BUY_ORDER_CREATED,
	BUY_ORDER_FILLED,
	BUY_ORDER_CANCELLED,
	QUEST_ACCEPTED,
	QUEST_OBJECTIVE,
	QUEST_COMPLETED
}
