package com.example.game.world.domain;

/**
 * Declared actions available at a location.
 */
public enum LocationAction {
	INSPECT,
	MOVE,
	VIEW_NEARBY,
	VIEW_CHAT,
	START_EXPEDITION,
	INSPECT_EXPEDITIONS,
	BROWSE_MARKET,
	CREATE_LISTING,
	BUY_ITEM,
	CANCEL_LISTING,
	SEARCH_ENCOUNTER,
	ENTER_DUNGEON,
	ENTER_ARENA,
	CHALLENGE_DUEL,
	START_SPARRING_DRILL,
	CRAFT,
	CLAIM_CRAFT,
	SALVAGE,
	CREATE_BUY_ORDER,
	FULFILL_BUY_ORDER,
	TALK_NPCS,
	NOTICE_BOARD
}
